openapi: 3.0.3

info:
  title: Swagger Books API - OpenAPI 3.0
  description: |-
    This is an API documentation for Books API based on the OpenAPI 3.0 specification.
    You can find out more about Swagger at [https://swagger.io](https://swagger.io). 
    This API will provide routes for various operations on Books, i.e. to create/read/update/delete exceptions.
  contact:
    email: muzaffarshaikh.projects@gmail.com
  version: 1.0.0

servers:
  - url: https://books-api.swagger.io/v1

tags:
  - name: book
    description: API routes for books
  # - name: author
  #   description: API routes for author
  # - name: series
  #   description: API routes for series

paths:
  /books:
    post:
      tags:
        - book
      summary: Add a new book
      description: Add a new book
      operationId: addBook
      requestBody:
        description: Create a new book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBookRequest'
        required: true
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBookResponse'          
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error

  /books/{id}:
    get:
      tags:
        - book
      summary: Get a book by ID
      description: Get a book by ID
      operationId: getBookByID
      parameters:
        - name: id
          in: path
          description: ID of book
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetBookResponse'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

    delete:
      tags:
        - book
      summary: Delete a book by ID
      description: Delete a book by ID
      operationId: deleteBookByID
      parameters:
        - name: id
          in: path
          description: ID of book
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                example:
                  success: true
                  deletedResourceID: 4a388b8a-74d3-46d9-ba7b-9a27f3b91a83
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
        isbn:
          type: string
          example: "0747532699"
        isbn13:
          type: string
          example: "9780747532699"
        title:
          type: string
          example: "The Philosophers Stone"
        author:
          type: object
          $ref: '#/components/schemas/Author'
        genre:
          type: array
        price:
          type: object
          $ref: '#/components/schemas/Price'
        pages:
          type: number
          example: 253
        language:
          type: string
          example: "English"
        coverPhotoURL:
          type: string
          example: "https://www.google.com"
        wikipediaURL:
          type: string
          example: https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone
        type:
          type: string
          example: Novel
          enum:
            - Novel
            - Manga
            - Comic Book
        publicationDate:
          type: string
          example: 26 June 1997
        series:
          type: object
          $ref: '#/components/schemas/Series'
        description:
          type: string
          example: "Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him."
      xml:
        name: book
    
    Author:
      type: object
      properties:
        id:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
        name:
          type: string
          example: J.K. Rowling
        country:
          type: string
          example: "United Kingdom"
        wikipediaURL:
          type: string
          example: "https://en.wikipedia.org/wiki/J._K._Rowling"
        profilePictureURL:
          type: string
          example: "https://en.wikipedia.org/wiki/J._K._Rowling"
      xml:
        name: author
    
    Price:
      type: object
      properties:
        currency:
          type: string
          example: INR
        amount:
          type: number
          example: 353.0
      xml:
        name: price
    
    Series:
      type: object
      properties:
        id:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
        name:
          type: string
          example: Harry Potter
        genre:
          type: array
        publisher:
          type: string
          example: Bloomsbury Publishing
        type:
          type: string
          example: Novel
          enum:
            - Novel
            - Manga
            - Comic Book
        numberOfBooks:
          type: number
          example: 7
        numberOfVolumes:
          type: number
          example: 0
        numberOfChapters:
          type: number
          example: 0
        authorID:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
      xml:
        name: series

    CreateBookRequest: 
      type: object
      required: 
        - isbn
        - isbn13
        - title
        - author
        - genre
        - language
        - coverPhotoURL
        - wikipediaURL
        - type
        - publicationDate
      properties:
        isbn:
          type: string
          example: "0747532699"
        isbn13:
          type: string
          example: "9780747532699"
        title:
          type: string
          example: "The Philosophers Stone"
        author:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: J.K. Rowling 
        genre:
          type: array
        price:
          type: object
          $ref: '#/components/schemas/Price'
        pages:
          type: number
          example: 253
        language:
          type: string
          example: "English"
        coverPhotoURL:
          type: string
          example: "https://www.google.com"
        wikipediaURL:
          type: string
          example: https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone
        type:
          type: string
          example: Novel
          enum:
            - Novel
            - Manga
            - Comic Book
        publicationDate:
          type: string
          example: 26 June 1997
        series:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: Harry Potter
        description:
          type: string
          example: "Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him."

    CreateBookResponse: 
      type: object
      properties:
        id:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
        isbn:
          type: string
          example: "0747532699"
        isbn13:
          type: string
          example: "9780747532699"
        title:
          type: string
          example: "The Philosophers Stone"
        author:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: J.K. Rowling 
        genre:
          type: array
        price:
          type: object
          $ref: '#/components/schemas/Price'
        pages:
          type: number
          example: 253
        language:
          type: string
          example: "English"
        coverPhotoURL:
          type: string
          example: "https://www.google.com"
        wikipediaURL:
          type: string
          example: https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone
        type:
          type: string
          example: Novel
          enum:
            - Novel
            - Manga
            - Comic Book
        publicationDate:
          type: string
          example: 26 June 1997
        series:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: Harry Potter
        description:
          type: string
          example: "Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him."

    GetBookResponse: 
      type: object
      properties:
        id:
          type: string
          example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
        isbn:
          type: string
          example: "0747532699"
        isbn13:
          type: string
          example: "9780747532699"
        title:
          type: string
          example: "The Philosophers Stone"
        author:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: J.K. Rowling 
        genre:
          type: array
        price:
          type: object
          $ref: '#/components/schemas/Price'
        pages:
          type: number
          example: 253
        language:
          type: string
          example: "English"
        coverPhotoURL:
          type: string
          example: "https://www.google.com"
        wikipediaURL:
          type: string
          example: https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone
        type:
          type: string
          example: Novel
          enum:
            - Novel
            - Manga
            - Comic Book
        publicationDate:
          type: string
          example: 26 June 1997
        series:
          type: object
          properties:
            id:
              type: string
              example: "4a388b8a-74d3-46d9-ba7b-9a27f3b91a83"
            name:
              type: string
              example: Harry Potter
        description:
          type: string
          example: "Harry Potter, an eleven-year-old orphan, discovers that he is a wizard and is invited to study at Hogwarts. Even as he escapes a dreary life and enters a world of magic, he finds trouble awaiting him."